In [ ]:
import numpy as np

a= np.array([[20,40],[60,80]])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [7]:
print(np.insert(a,[1,2],[50], axis = 0)) #array,index,value

[[20 40]
 [50 50]
 [60 80]
 [50 50]]


In [11]:
print(a)
print()
print(np.delete(a,1, axis =1))

[[20 40]
 [60 80]]

[[20]
 [60]]
