In [5]:
import numpy as np

arr= np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
print (np.shape(arr))
print(np.size(arr))
print (np.ndim(arr))
print (arr.dtype)
print(arr[2,2])

(3, 4)
12
2
int64
60


In [ ]:
# inspecting an array

import numpy as np

a= [[30,40,40],[20,40,30.8]]
arr= np.array(a)
print(arr)
print(arr.shape) #rows, colums
print(len(arr)) #number  of nested values
print(np.size(arr)) #number of elements
print(type(arr)) #type of variable
print(arr.dtype) #data type of array
print(arr.astype(int)) #conversion of data type

[[30.  40.  40. ]
 [20.  40.  30.8]]
(2, 3)
2
6
<class 'numpy.ndarray'>
float64
[[30 40 40]
 [20 40 30]]
