In [5]:
import numpy as np

arr1 = np.array([[30,40],[60,20]])
arr2 = ([[30,20],[10,20]])
print(arr1+arr2)
print(np.add(arr1,arr2,))

[[60 60]
 [70 40]]
[[60 60]
 [70 40]]


In [ ]:
import numpy as np

arr1 = np.array([[30,40],[60,20]])
arr2 = ([[30,20],[10,20]])
print(arr1-arr2)
print(np.subtract(arr1,arr2,))

[[ 0 20]
 [50  0]]
[[ 0 20]
 [50  0]]


In [7]:
import numpy as np

arr1 = np.array([[30,40],[60,20]])
arr2 = ([[30,20],[10,20]])
print(arr1*arr2)
print(np.multiply(arr1,arr2,))


[[900 800]
 [600 400]]
[[900 800]
 [600 400]]


In [8]:
import numpy as np

arr1 = np.array([[30,40],[60,20]])
arr2 = ([[30,20],[10,20]])
print(arr1/arr2)
print(np.divide(arr1,arr2,))


[[1. 2.]
 [6. 1.]]
[[1. 2.]
 [6. 1.]]


In [12]:
arr1 = np.array([3,4,2,1])
arr2 = np.array([2])
print(np.power(arr1,arr2))

[ 9 16  4  1]


In [13]:
arr1= np.array([9, 16, 4, 1])
print(np.sqrt(arr1))

[3. 4. 2. 1.]
