In [5]:

import numpy as np 

a = np.array([20,30,40])
b = np.array([60,70,80])
print(a)
print(b)
print(a+b)



[20 30 40]
[60 70 80]
[ 80 100 120]


In [8]:
a = np.array([40,50,"60"])
print(a)

['40' '50' '60']


In [3]:
l1 = [20,30,40]
l2 = [50,60,70]
print(l1+l2)

[20, 30, 40, 50, 60, 70]
