In [2]:
import numpy as np
arr= np.array([[7,8,4,12,9],[2,8,5,1,3]])
print(np.sort(arr))

[[ 4  7  8  9 12]
 [ 1  2  3  5  8]]


In [4]:
ar= np.array([3,4,1,7,8])
s = np.where(ar % 2 == 0)
print(s)

(array([1, 4]),)


In [ ]:
ar= np.array([1,2,3,4,5]) #searchsorted
ss= np.searchsorted(ar,5)
print(ss)

4


In [ ]:
ar= np.array([20,30,40,50]) #FILTER ARRAY

fa= [True, False, True, False]

new= ar[fa]
print(new)

[20 40]


In [10]:
ar = np.array([2,3,4,5])

fa = ar%2==0

new = ar[fa]
print(new)

[2 4]
